### ISSUE TITLE
I will add README to the project 

### ISSUE THREAD

**Issue by SusheelThapa** [srbmaury/tic-tac-toe#2]
README will look like:
![Screenshot from 2023-10-01 17-22-08](https://github.com/srbmaury/tic-tac-toe/assets/83917129/a96901f8-42d2-4787-9985-3947d7f8e6c2)

**Comment by SusheelThapa** [comment]
@srbmaury Can you shsre following details?

Project Short description
Project logo
Short video of the project

**Comment by SusheelThapa** [comment]
@srbmaury  your email

**Comment by srbmaury** [comment]
> @srbmaury Can you shsre following details?
> 
> Project Short description Project logo Short video of the project

**Description:** It is a project that features a Tic Tac Toe game with two modes. One mode allows you to play against an unbeatable computer opponent that uses the [Minimax algorithm](https://www.geeksforgeeks.org/finding-optimal-move-in-tic-tac-toe-using-minimax-algorithm-in-game-theory/), while the other mode is for playing with a friend. The game also includes a scoring system and a user-friendly interface for easy and enjoyable gameplay.

**Email:** srbmaury@gmail.com

You may design a logo and make a short video on your own.

**Comment by SusheelThapa** [comment]
@srbmaury 


# Code of Conduct

## Introduction

We, as contributors and maintainers, pledge to make participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

We are committed to providing a friendly, safe, and welcoming environment for all, regardless of gender, sexual orientation, disability, ethnicity, religion, or similar personal characteristics.

## Our Standards

Examples of behavior that contributes to creating a positive environment include:

- Using welcoming and inclusive language.
- Being respectful of differing viewpoints and experiences.
- Gracefully accepting constructive criticism.
- Focusing on what is best for the community.
- Showing empathy towards other community members.

Examples of unacceptable behavior by participants include:

- The use of sexualized language or imagery and unwelcome sexual attention or advances.
- Trolling, insulting/derogatory comments, and personal or political attacks.
- Public or private harassment.
- Publishing others' private information, such as physical or electronic addresses, without explicit permission.
- Other conduct that could reasonably be considered inappropriate in a professional setting.

## Our Responsibilities

Project maintainers are responsible for clarifying the standards of acceptable behavior and are expected to take appropriate and fair corrective action in response to any instances of unacceptable behavior.

Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned with this Code of Conduct or to ban temporarily or permanently any contributor for other behaviors that they deem inappropriate, threatening, offensive, or harmful.

## Enforcement

Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at [srbmaury@gmail.com](mailto:srbmaury@gmail.com). All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality with regard to the reporter of an incident. Further details of specific enforcement policies may be posted separately.

Project maintainers who do not follow or enforce the Code of Conduct in good faith may face temporary or permanent repercussions as determined by other members of the project's leadership.

**Comment by SusheelThapa** [comment]
This is Code of Conduct file, check once

**Comment by srbmaury** [comment]
Please add only the readme file. I believe there is no need of any such
code of conduct file.
