### ISSUE TITLE
Resizing the tic-tac-toe UI so that it fits in the desktop screen

### ISSUE THREAD

**Issue by ayushsgit** [srbmaury/tic-tac-toe#3]

**Comment by ayushsgit** [comment]
The Tic-tac-toe player screen is way out of bounds for the desktop screen, I will try to adjust it so the user can play the game without resizing the screen every single time

**Comment by srbmaury** [comment]
It looks good in my screen.
![image](https://github.com/srbmaury/tic-tac-toe/assets/85755081/001915de-f73d-4c89-9d20-dc71c79945bd)
Can you please attach a screenshot?

**Comment by ayushsgit** [comment]
![image](https://github.com/srbmaury/tic-tac-toe/assets/115374687/89d4902a-221b-4ff7-97d2-e62850dea47c)
it looks like this and when we resize to 30% it looks visible
![image](https://github.com/srbmaury/tic-tac-toe/assets/115374687/b61bf3cb-6391-4bc8-b1fe-75d79179d458)

**Comment by srbmaury** [comment]
you may proceed.

**Comment by ayushsgit** [comment]
after a lot of figuring out , adding a scrollbar was a feasible option
https://melodious-syrniki-3ee822.netlify.app/
you might be able to improve it further by your knowledge
if you like to solve the issue further i would PR this ,
else i was not able to figure this out and you can close this issue

**Comment by srbmaury** [comment]
let others see if they can do better.

**Comment by TOLU-MICH** [comment]
hi, please can you assign me i'd like to work on the user interface

**Comment by srbmaury** [comment]
> hi, please can you assign me i'd like to work on the user interface

Before I assign you this task, are you also seeing a similar UI to what Ayush has sent above?

**Comment by SusheelThapa** [comment]
@srbmaury  I am also having same problem.

**Comment by TOLU-MICH** [comment]
it looks good on my screen

**Comment by srbmaury** [comment]
> it looks good on my screen

You may work on the issue if you want to make UI better.

**Comment by srbmaury** [comment]
#9
