### ISSUE TITLE
Make Proper Folder Structure

### ISSUE THREAD

**Issue by srbmaury** [srbmaury/tic-tac-toe#7]
![image](https://github.com/srbmaury/tic-tac-toe/assets/85755081/138a49f0-9a98-4b34-9432-a0246fdf451f)
Make this more presentable

**Comment by SusheelThapa** [comment]
@srbmaury  assign me thsi task

**Comment by SusheelThapa** [comment]
@srbmaury  can you label my other pull request that has been merged to hacktoberfest-accepted

**Comment by srbmaury** [comment]
To be accepted in Hacktoberfest either the repository should have a
Hacktoberfest label or The PR should have a Hacktoberfest-accepted label
(any of them will do the job) and this repository already has a
Hacktoberfest label.

Please avoid writing such unnecessary comments everywhere.

**Comment by ShrutiKolla** [comment]
@srbmaury please assign me this issue

**Comment by srbmaury** [comment]
@ShrutiKolla it has already been done.

**Comment by srbmaury** [comment]
#8

**Comment by ShrutiKolla** [comment]
@srbmaury oh, the issue has been resolved?
